# Generated by Django 3.0.3 on 2020-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chicken', models.BooleanField(default=False)),
                ('eggs', models.BooleanField(default=False)),
                ('oil', models.BooleanField(default=False)),
                ('masala', models.BooleanField(default=False)),
                ('ginger', models.BooleanField(default=False)),
            ],
        ),
    ]
