# Generated by Django 3.0.3 on 2020-05-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200524_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
